In [1]:
# Construct a pandas DataFrame using `read()`
import pandas as pd

df = pd.read_csv("./datasets/bbc_text_cls.csv")
df

text    labels
0     Ad sales boost Time Warner profit\n\nQuarterly...  business
1     Dollar gains on Greenspan speech\n\nThe dollar...  business
2     Yukos unit buyer faces loan claim\n\nThe owner...  business
3     High fuel prices hit BA's profits\n\nBritish A...  business
4     Pernod takeover talk lifts Domecq\n\nShares in...  business
...                                                 ...       ...
2220  BT program to beat dialler scams\n\nBT is intr...      tech
2221  Spam e-mails tempt net shoppers\n\nComputer us...      tech
2222  Be careful how you code\n\nA new European dire...      tech
2223  US cyber security chief resigns\n\nThe man mak...      tech
2224  Losing yourself in online gaming\n\nOnline rol...      tech

[2225 rows x 2 columns]

# 1. Vocabulary
Create **Vocabulary** dictionaries:
- **word2idx:** All the unique words as keys with a corresponding unique ID as values.
- **idx2word:** The reverse of word2idx. It has the unique IDs as keys and their corresponding words as values.

# 1-1. word2idx

# 1-2. idx2word

# 2. One-Hot Encoding
The process of one-hot encoding involves **Vocabulary Creation** & **Vector Representation** two steps.

1. Manual Implementation.
2. `pandas.get_dummies(data, prefix=None, prefix_sep='_', dummy_na=False, columns=None, sparse=False, drop_first=False, dtype=None)`
3. `sklearn.preprocessing.OneHotEncoder(*, categories='auto', drop=None, sparse_output=True, dtype=<class 'numpy.float64'>, handle_unknown='error', min_frequency=None, max_categories=None, feature_name_combiner='concat')`
4. `tf.keras.utils.to_categorical(x, num_classes)`

In [9]:
# Create a set of unique words in the corpus
import random

unique_words = set()
for doc in df["text"]:
    for word in doc.split():
        unique_words.add(word.lower())

# Sample 100 words
print(random.sample(tuple(unique_words), 100))

['betts-green,', "d'amuro", 'threat', 'glowing', 'work', 'colder."', 'court-imposed', 'persuasive', '4%,', 'slams.', 'proven', 'seamen', '"arrogant', '"otherwise', 'last-eight', 'beckons', 'pickups,', 'persecuted."', 'constantly', 'slightly.', 'excessively', 'striker,', '(australia)', '(2.1', 'together', 'stop', 'razr', '1980s.', "commission's", 'ubiquitous', 'sheffield-born', 'costs,"', 'catholics', 'merchandising', 'koumas', 'nintendo,', 'stops', 'wray,', 'mccabe', 'shove.', 'fraction', 'sexual', 'hearty', 'hegedus,', 'burnley,', 'voldemort', 'visitor', 'deon', 'unpaid', 'departure,"', 'squirreling', 'striking.', 'course."', 'gallery,"', 'cherie', '(henman).', 'created,', 'rj', 'beating"', '$111m', 'peek', "can't", 'bruvik', '6.67', "dragon's", 'harinordoquy', 'make-up', '19.6', 'formal', 'axa', 'birthdays.', 'friday?', 'intent,', 'bellamy,', 'nishioka,', "regiments'", 'bertie', 'kaha', 'susanne', 'divert', 'crying', 'non-opec', 'sprinter.', 'arrangements."', '(bpd),', 'prize-fighter

In [10]:
# Create a dictionary to map each unique word to an index
import itertools

word2idx = {}
for idx, word in enumerate(unique_words):
    word2idx[word] = idx

# Return first 100 items
print(list(itertools.islice(word2idx.items(), 100)))

[('hinckley,', 0), ('bucking', 1), ('stores."', 2), ('8.6bn', 3), ('12.37', 4), ('osborne', 5), ('egelton,', 6), ('path,', 7), ('pay-out', 8), ('miller.', 9), ('most,', 10), ('struggling', 11), ("sender's", 12), ('activities,', 13), ('satirist', 14), ('3,217', 15), ('(team', 16), ('original.', 17), ('mac,"', 18), ('hughes.', 19), ('a$846m', 20), ('advanced,', 21), ('receivers', 22), ('intervention', 23), ('attack."', 24), ('"audioblogs"', 25), ('esson,', 26), ('assault,', 27), ('layout', 28), ('campaiging', 29), ('agency.', 30), ('kezman', 31), ('vein', 32), ('filmmaker', 33), ("employee's", 34), ('fatboy', 35), ('6,000-strong', 36), ('printers', 37), ('shield', 38), ('ingots', 39), ('leave.', 40), ('aid', 41), ('management."', 42), ('1920s.', 43), ('robber', 44), ('difference"', 45), ('puzzlement', 46), ('"musicians', 47), ('developed,', 48), ('aids,', 49), ('weh', 50), ('75p', 51), ('frisk,', 52), ('villagers', 53), ('lange', 54), ('serena)', 55), ('masayuki', 56), ('uk-controlled', 

## 2-1. Manual One-Hot Encoding
Each word is represented as a vector of `0`s and `1`s. The length of the vector is equal to the size of the vocabulary. Position in the vector corresponds to a specific word in the vocabulary. If the word is present in a particular text sample, its corresponding position in the vector is marked as `1`, and all other positions are `0`. This implies that each word is uniquely represented by a binary vector, with only one element being `1`, indicating its presence, and all others being `0`.

In [4]:
# Create one-hot encoded vectors for each word in the corpus
import numpy as np

one_hot_vec = []
for doc in df['text']:
    doc_vec = []
    for word in doc.split():
        vec = np.zeros(len(unique_words))
        vec[word2idx[word.lower()]] = 1
        doc_vec.append(vec)
    one_hot_vec.append(doc_vec)

# One-hot encoded vectors of the first 10 words from the first document
for i in range(10):
    print(one_hot_vec[0][i])

[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]


## 2-2. One-Hot Encoding with pandas

In [ ]:
import pandas as pd

one_hot_encoded_doc = pd.get_dummies(df['text'][0], )

## 2-3. One-Hot Encoding with scikit-learn

In [16]:
# Split documents to tokens

tokens_docs = [doc.lower().split() for doc in df['text']]

# Convert token lists to token-id lists
token_ids = [[word2idx[token] for token in tokens_doc] for tokens_doc in tokens_docs]
print(token_ids[0])

[31692, 45964, 32112, 31249, 53725, 31989, 7696, 4698, 54745, 24126, 16396, 54296, 16577, 56309, 34658, 9114, 45581, 16860, 2541, 8862, 37069, 55973, 9114, 2030, 56064, 58174, 13785, 8862, 24501, 40244, 13911, 25292, 43053, 33388, 8862, 9720, 17127, 21676, 48607, 39588, 56064, 45964, 33388, 9533, 42564, 24866, 27275, 16155, 22174, 39243, 16577, 26770, 43155, 24259, 45964, 27050, 55352, 9114, 45397, 56064, 45760, 22398, 4698, 48483, 20745, 17964, 2700, 4733, 40244, 11483, 17546, 31989, 33049, 54745, 53725, 15436, 27275, 39648, 49671, 2541, 6576, 31249, 53725, 26770, 36693, 54189, 44565, 47792, 25292, 56974, 14032, 33388, 16752, 10759, 51712, 22398, 21806, 42564, 56441, 27634, 25581, 15694, 26344, 51061, 47792, 24931, 33240, 59146, 21676, 8862, 43155, 24259, 4698, 48483, 57681, 31936, 21676, 8862, 57961, 37069, 22764, 30840, 8862, 28483, 26770, 56328, 32225, 31989, 34634, 58913, 51346, 27050, 14032, 36693, 8862, 54625, 33388, 20209, 42564, 60230, 43614, 47792, 55761, 9114, 13394, 59146, 

In [21]:
from sklearn.preprocessing import OneHotEncoder

# Convert list of token-id lists to one-hot representation
vec = OneHotEncoder(categories=list(unique_words))
X = vec.fit_transform(token_ids)
print(X.toarray())

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2225,) + inhomogeneous part.

## 2-4. One-Hot Encoding with Keras

# 2. Bag-of-Words (BoW)
## 2-1. Manual Implementation

## 2-2. CountVectorizer

# 3. TF-IDF
## 3-1. Manual Implementation
### 3-1-1. word2idx

In [ ]:
import nltk
nltk.download('punkt')

In [ ]:
from nltk import word_tokenize

words = word_tokenize(df["text"][0])
print(words)

In [ ]:
# Populate word2idx
# Convert documents into sequences of ints / ids / indices
idx = 0
word2idx = {}
tokenized_docs = []

for doc in df["text"]:
    words = word_tokenize(doc.lower())
    doc_as_int = []
    for word in words:
        if word not in word2idx:
            word2idx[word] = idx
            idx += 1
        # Save for later
        doc_as_int.append(word2idx[word])
    tokenized_docs.append(doc_as_int)

tokenized_docs

### 3-1-2. idx2word

In [ ]:
# Reverse mapping
idx2word = {v:k for k, v in word2idx.items()}
idx2word

In [ ]:
# Number of documents
N = len(df['text'])

# Number of words
V = len(word2idx)

N, V

### 3-1-3. Term Frequency (TF)
**Term frequency (TF)** means how often a term occurs in a document.

In [ ]:
import numpy as np

# Instantiate term-frequency matrix
tf = np.zeros((N, V))

# Populate term-frequency counts
for i, doc_as_int in enumerate(tokenized_docs):
    for j in doc_as_int:
        tf[i, j] += 1

tf

### 3-1-4. Inverse Document Frequency (IDF)
- **Document frequency (DF)** is the number of documents containing a particular term.
- **Inverse Document Frequency (IDF)** is a weight indicating how commonly a word is used.

In [ ]:
# Compute IDF
# `axis=0` is the direction running downward the rows
doc_freq = np.sum(tf > 0, axis=0)
idf = np.log(N / doc_freq)
idf

In [ ]:
### TF-IDF

In [ ]:
# Compute TF-IDF
tf_idf = tf * idf
tf_idf

In [ ]:
# Pick a random document, show the top 5 terms (in terms of `tf_idf` score)
np.random.seed(36)
i = np.random.choice(N)
row = df.iloc[i]
print("Label:", row['label'])
print("Text:", row['text'].split("\n", 1)[0])
print("Top 5 terms:")

scores = tf_idf[i]
# Add minus for descending
indices = (-scores).argsort()
for j in indices[:5]:
    print(idx2word[j])

## 3-2. CountVectorizer
Derived term frequencies from `CountVectorizer`.

In [ ]:
inputs = df["text"]
labels = df["label"]

labels.hist(figsize=(10, 5));

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
tf = vectorizer.fit_transform(inputs)
words = vectorizer.get_feature_names_out()
print(words)

In [ ]:
tf

In [ ]:
print(tf.toarray())

In [ ]:
# Fewer words than `nltk.word_tokenize()`
tf.shape

In [ ]:
# By default `lowercase=True`
# np.where(words == "India")
# (array([], dtype=int64),)

# By default `token_pattern=r”(?u)\b\w\w+\b`
# RegExp selects tokens of 2 or more alphanumeric characters (punctuation is completely ignored and always treated as a token separator)
# np.where(words == "$")
# (array([], dtype=int64),)

np.where(words == "india")

In [ ]:
# Same as `tf[0][0]` in the above section
tf.toarray()[0][13907]

In [ ]:
# Compute IDF
doc_freq = np.sum(tf.toarray() > 0, axis=0)
idf = np.log(N / doc_freq)
idf

In [ ]:
# Compute TF-IDF
tf_idf = tf.toarray() * idf
tf_idf

In [ ]:
tf_idf.shape

In [ ]:
# Same as `tf_idf[0][0]` in the above section
tf_idf[0][13907]

## 3-3. TfidfTransformer

In [ ]:
from sklearn.feature_extraction.text import TfidfTransformer

transformer = TfidfTransformer()
tf_idf = transformer.fit_transform(tf)
words = vectorizer.get_feature_names_out()
print(words)

In [ ]:
tf_idf

In [ ]:
# The `sklearn` implementation of TF-IDF is different from our manual implementation 
print(tf_idf.toarray())

## 3-4. TfidfVectorizer

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
tf_idf = vectorizer.fit_transform(inputs)
words = vectorizer.get_feature_names_out()
print(words)

In [ ]:
tf_idf

In [ ]:
# Same as `CountVectorizer()` followed by `TfidfTransformer()`
print(tf_idf.toarray())

Perform classification.

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

inputs_train, inputs_test, y_train, y_test = train_test_split(inputs, labels, random_state=36)

vectorizer = CountVectorizer()

x_train = vectorizer.fit_transform(inputs_train)
x_test = vectorizer.transform(inputs_test)

model = MultinomialNB()
model.fit(x_train, y_train)

print("Train Score:", model.score(x_train, y_train))
print("Test Score:", model.score(x_test, y_test))

# 4. word2vec
## 4-1. CBOW (Continuous Bag of Words)
## 4-2. Skip-Gram
# 5. GloVe
# 6. FastText
# 7. Gaussian Embedding
# 8. Pointcare Embedding