In [2]:
import torch

# 1. PyTorch Tensors

In [3]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# matrix
matrix = torch.tensor([[1, 2], [3, 4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [11]:
matrix[0]

tensor([1, 2])

In [12]:
matrix.ndim

2

In [10]:
matrix.shape

torch.Size([2, 2])

In [13]:
# Tensor
tensor = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [16]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [17]:
tensor[0][1]

tensor([4, 5, 6])

In [14]:
tensor.ndim

3

In [15]:
tensor.shape

torch.Size([1, 3, 3])

## 1-1. Random

In [ ]:
# Set the random seed
RANDOM_SEED = 100
torch.manual_seed(RANDOM_SEED)

In [19]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.0730, 0.4797, 0.9343, 0.2787],
        [0.5118, 0.5053, 0.8628, 0.2954],
        [0.1912, 0.8626, 0.3521, 0.0279]])

In [21]:
random_tensor = torch.rand(size=(3, 224, 224))
random_tensor

tensor([[[0.1026, 0.3164, 0.0788,  ..., 0.8504, 0.7301, 0.9744],
         [0.3827, 0.1933, 0.1453,  ..., 0.1690, 0.5638, 0.6830],
         [0.5310, 0.5235, 0.5262,  ..., 0.8321, 0.4081, 0.1552],
         ...,
         [0.3136, 0.2305, 0.3834,  ..., 0.5960, 0.7216, 0.9114],
         [0.4767, 0.6360, 0.7722,  ..., 0.0981, 0.4069, 0.3725],
         [0.1342, 0.0999, 0.0238,  ..., 0.7767, 0.7813, 0.3495]],

        [[0.2750, 0.3080, 0.6140,  ..., 0.4562, 0.4973, 0.5639],
         [0.6847, 0.7653, 0.3971,  ..., 0.7869, 0.9829, 0.6039],
         [0.7455, 0.2357, 0.7595,  ..., 0.5343, 0.6318, 0.8577],
         ...,
         [0.5081, 0.5969, 0.7765,  ..., 0.8612, 0.0925, 0.7518],
         [0.0529, 0.3172, 0.6430,  ..., 0.4596, 0.8803, 0.6801],
         [0.1798, 0.1344, 0.4809,  ..., 0.8248, 0.5686, 0.6871]],

        [[0.9628, 0.9303, 0.2978,  ..., 0.3283, 0.0120, 0.6298],
         [0.5651, 0.7603, 0.1950,  ..., 0.6793, 0.7566, 0.4832],
         [0.5141, 0.0545, 0.4909,  ..., 0.7836, 0.4998, 0.

In [23]:
random_tensor.ndim

3

In [22]:
random_tensor.shape

torch.Size([3, 224, 224])

## 1-2. Zeros & Ones

In [24]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [25]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [26]:
# `torch.arange()`
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## 1-3. Data Types
- [Data Types](https://pytorch.org/docs/stable/tensors.html#data-types)

In [28]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [29]:
float_32_tensor.dtype

torch.float32

In [30]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [31]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

## 1-4. Manipulation

In [32]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [33]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [34]:
# Substract 10
tensor - 10

tensor([-9, -8, -7])

In [35]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [36]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

## 1-5. Matrix Multiplication

In [37]:
# Element wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [39]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [38]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [42]:
tensor @ tensor

tensor(14)

In [40]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.34 ms, sys: 170 µs, total: 1.51 ms
Wall time: 10.2 ms


In [41]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 800 µs, sys: 0 ns, total: 800 µs
Wall time: 694 µs


tensor(14)

## 1-6. Aggregation

In [43]:
one_to_ten.min()

tensor(1)

In [44]:
torch.min(one_to_ten)

tensor(1)

In [45]:
one_to_ten.max()

tensor(10)

In [46]:
torch.max(one_to_ten)

tensor(10)

In [48]:
one_to_ten.type(torch.float32).mean()

tensor(5.5000)

In [47]:
torch.mean(one_to_ten.type(torch.float32))

tensor(5.5000)

In [49]:
one_to_ten.sum()

tensor(55)

In [50]:
torch.sum(one_to_ten)

tensor(55)

## 1-7. Positional Min & Max

In [51]:
one_to_ten.argmin()

tensor(0)

In [52]:
one_to_ten[0]

tensor(1)

In [53]:
one_to_ten.argmax()

tensor(9)

In [54]:
one_to_ten[9]

tensor(10)

## 1-8. Reshaping, Stacking, Squeezing & Unsqueezing

In [55]:
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
one_to_ten.shape

torch.Size([10])

In [57]:
one_to_ten_reshaped = one_to_ten.reshape(1, 10)
one_to_ten_reshaped

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [62]:
one_to_ten_reshaped.shape

torch.Size([1, 10])

In [58]:
one_to_ten_stacked = torch.stack([one_to_ten, one_to_ten, one_to_ten, one_to_ten], dim=0)
one_to_ten_stacked

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [61]:
one_to_ten_stacked.shape

torch.Size([4, 10])

In [63]:
# Remove extra dimensions
one_to_ten_squeezed = one_to_ten_reshaped.squeeze()
one_to_ten_squeezed 

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
one_to_ten_squeezed.shape

torch.Size([10])

In [66]:
# Add an extra dimension with `unsqueeze()`
one_to_ten_unsqueezed = one_to_ten_squeezed.unsqueeze(dim=0)
one_to_ten_unsqueezed

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [67]:
one_to_ten_unsqueezed.shape

torch.Size([1, 10])

In [70]:
random_tensor.shape

torch.Size([3, 224, 224])

In [68]:
# `permute()`
random_tensor_permuted = random_tensor.permute(2, 0, 1)
random_tensor_permuted

tensor([[[0.1026, 0.3827, 0.5310,  ..., 0.3136, 0.4767, 0.1342],
         [0.2750, 0.6847, 0.7455,  ..., 0.5081, 0.0529, 0.1798],
         [0.9628, 0.5651, 0.5141,  ..., 0.6006, 0.4456, 0.6274]],

        [[0.3164, 0.1933, 0.5235,  ..., 0.2305, 0.6360, 0.0999],
         [0.3080, 0.7653, 0.2357,  ..., 0.5969, 0.3172, 0.1344],
         [0.9303, 0.7603, 0.0545,  ..., 0.8932, 0.9240, 0.7944]],

        [[0.0788, 0.1453, 0.5262,  ..., 0.3834, 0.7722, 0.0238],
         [0.6140, 0.3971, 0.7595,  ..., 0.7765, 0.6430, 0.4809],
         [0.2978, 0.1950, 0.4909,  ..., 0.1631, 0.6309, 0.6182]],

        ...,

        [[0.8504, 0.1690, 0.8321,  ..., 0.5960, 0.0981, 0.7767],
         [0.4562, 0.7869, 0.5343,  ..., 0.8612, 0.4596, 0.8248],
         [0.3283, 0.6793, 0.7836,  ..., 0.9614, 0.0232, 0.5641]],

        [[0.7301, 0.5638, 0.4081,  ..., 0.7216, 0.4069, 0.7813],
         [0.4973, 0.9829, 0.6318,  ..., 0.0925, 0.8803, 0.5686],
         [0.0120, 0.7566, 0.4998,  ..., 0.6367, 0.7797, 0.8528]],

 

In [69]:
random_tensor_permuted.shape

torch.Size([224, 3, 224])

## 1-9. NumPy Arrays

In [71]:
import numpy as np

array = np.arange(1.0, 11.0)
array

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [72]:
# `torch.from_numpy()`
tensor = torch.from_numpy(array)
tensor

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=torch.float64)

In [78]:
# `numpy()`
tensor = torch.arange(start=1.0, end=11.0, step=1.0)
numpy_tensor = tensor.numpy()
numpy_tensor 

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

In [79]:
numpy_tensor.dtype

dtype('float32')

# 2. GPU

In [80]:
!nvidia-smi

Mon Aug  5 20:01:59 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.183.01             Driver Version: 535.183.01   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4090 ...    Off | 00000000:01:00.0  On |                  N/A |
| N/A   45C    P8               3W /  80W |   2999MiB / 16376MiB |      6%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [81]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

In [82]:
# Setup device agnostic code 
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [83]:
# Count number of devices
torch.cuda.device_count()

1

In [84]:
tensor.device

device(type='cpu')

In [85]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], device='cuda:0')

In [86]:
tensor_on_gpu.device

device(type='cuda', index=0)

In [87]:
tensor_on_cpu = tensor_on_gpu.cpu()
tensor_on_cpu

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [88]:
tensor_on_cpu.device

device(type='cpu')