In [2]:
import torch

# 1. Tensors

In [3]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# matrix
matrix = torch.tensor([[1, 2], [3, 4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [11]:
matrix[0]

tensor([1, 2])

In [12]:
matrix.ndim

2

In [10]:
matrix.shape

torch.Size([2, 2])

In [13]:
# Tensor
tensor = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [16]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [17]:
tensor[0][1]

tensor([4, 5, 6])

In [14]:
tensor.ndim

3

In [15]:
tensor.shape

torch.Size([1, 3, 3])

## 1-1. Random

In [19]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.0730, 0.4797, 0.9343, 0.2787],
        [0.5118, 0.5053, 0.8628, 0.2954],
        [0.1912, 0.8626, 0.3521, 0.0279]])

In [21]:
random_tensor = torch.rand(size=(3, 224, 224))
random_tensor

tensor([[[0.1026, 0.3164, 0.0788,  ..., 0.8504, 0.7301, 0.9744],
         [0.3827, 0.1933, 0.1453,  ..., 0.1690, 0.5638, 0.6830],
         [0.5310, 0.5235, 0.5262,  ..., 0.8321, 0.4081, 0.1552],
         ...,
         [0.3136, 0.2305, 0.3834,  ..., 0.5960, 0.7216, 0.9114],
         [0.4767, 0.6360, 0.7722,  ..., 0.0981, 0.4069, 0.3725],
         [0.1342, 0.0999, 0.0238,  ..., 0.7767, 0.7813, 0.3495]],

        [[0.2750, 0.3080, 0.6140,  ..., 0.4562, 0.4973, 0.5639],
         [0.6847, 0.7653, 0.3971,  ..., 0.7869, 0.9829, 0.6039],
         [0.7455, 0.2357, 0.7595,  ..., 0.5343, 0.6318, 0.8577],
         ...,
         [0.5081, 0.5969, 0.7765,  ..., 0.8612, 0.0925, 0.7518],
         [0.0529, 0.3172, 0.6430,  ..., 0.4596, 0.8803, 0.6801],
         [0.1798, 0.1344, 0.4809,  ..., 0.8248, 0.5686, 0.6871]],

        [[0.9628, 0.9303, 0.2978,  ..., 0.3283, 0.0120, 0.6298],
         [0.5651, 0.7603, 0.1950,  ..., 0.6793, 0.7566, 0.4832],
         [0.5141, 0.0545, 0.4909,  ..., 0.7836, 0.4998, 0.

In [23]:
random_tensor.ndim

3

In [22]:
random_tensor.shape

torch.Size([3, 224, 224])

## 1-2. Zeros & Ones